version: '3'

services:
  testnginx:
    image: nginx
    container_name: testnginx
    ports:
      - "80:80"
    volumes:
      - ~/Projects/sh-valley/docker-conf/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ~/Projects/sh-valley/docker-conf/nginx/www:/usr/share/nginx/html
      - ~/Projects/sh-valley/docker-conf/nginx/logs:/var/log/nginx

