version: "2.1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    hostname: elasticsearch
    expose: 
      - "9001"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=single-node-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-network
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.4
    ports:
      - "5601:5601"
    volumes:
      - /usr/share/kibana/config/kibana.xml:/Users/shiqiang/Projects/sh-valley/docker-conf/elasticstack/es-kibana/kibana.xml
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - es-network
networks:
  es-network:
